/**
 * PAINEL DE ASSUNTOS — dados de demonstração (modo fixture).
 *
 * Serve a tela sem tocar no Supabase: é com isto que se desenvolve, se tira
 * screenshot e se roda o build. As datas são calculadas a partir de um `agora`
 * injetado — assim a demonstração nunca "envelhece" e continua mostrando os
 * quatro estados (esperando · andando · parado · fechado) em qualquer dia.
 *
 * Cobre de propósito: mudança já na versão oficial, mudança descartada,
 * rascunho, testes ok / com erro / rodando / sem resultado, trabalho commitado
 * sem conversa ligada, conversa sem mudança nenhuma, item fora da janela de 30
 * dias (só aparece no histórico) e uma fonte de dados velha (acende o aviso).
 */

import type { BranchSemPr, DadosFrentes, Pr, Sessao, Sync } from "@/lib/frentes/types";

const HORA = 3_600_000;
const DIA = 24 * HORA;

const LUCAS = "lucasscudeler@gmail.com";
const PANDORA = "lsgpandora@gmail.com";
const ALMA = "almapetra.ltda@gmail.com";

const HUB = "scudelerlucas/Lucas-Contexto-Geral";
const QUIZ = "scudelerlucas/quiz-diagnosys";
const ALMA_OS = "scudelerlucas/alma-petra-os";
const AIOX = "scudelerlucas/aiox-core";

/** Monta o pacote de demonstração relativo a `agora` (ms). */
export function fixtureFrentes(agora: number = Date.now()): DadosFrentes {
  /** ISO de "h horas atrás". */
  const h = (horas: number): string => new Date(agora - horas * HORA).toISOString();
  /** ISO de "d dias atrás". */
  const d = (dias: number): string => new Date(agora - dias * DIA).toISOString();

  const prs: Pr[] = [
    {
      repo: HUB,
      numero: 612,
      titulo: "feat(painel): quadro de assuntos das três contas",
      estado: "aberto",
      rascunho: false,
      branch: "claude/painel-assuntos",
      base: "main",
      autor: "claude",
      url: "https://github.com/scudelerlucas/Lucas-Contexto-Geral/pull/612",
      criado_em: h(9),
      atualizado_em: h(2),
      fechado_em: null,
      mergeado_em: null,
      sessao_ids: ["sess_painel_01"],
      labels: ["painel"],
      checks: "verde",
      sincronizado_em: h(0.6),
    },
    {
      repo: HUB,
      numero: 610,
      titulo: "chore(vigia): lista de domínios do vigia de uptime",
      estado: "aberto",
      rascunho: true,
      branch: "claude/vigia-uptime",
      base: "main",
      autor: "claude",
      url: "https://github.com/scudelerlucas/Lucas-Contexto-Geral/pull/610",
      criado_em: h(20),
      atualizado_em: h(1),
      fechado_em: null,
      mergeado_em: null,
      sessao_ids: ["sess_vigia_02"],
      labels: [],
      checks: "pendente",
      sincronizado_em: h(0.6),
    },
    {
      repo: QUIZ,
      numero: 88,
      titulo: "feat(quiz): grava as métricas do ser em quiz_leituras",
      estado: "aberto",
      rascunho: false,
      branch: "claude/quiz-idforge",
      base: "main",
      autor: "claude",
      url: "https://github.com/scudelerlucas/quiz-diagnosys/pull/88",
      criado_em: d(2),
      atualizado_em: h(5),
      fechado_em: null,
      mergeado_em: null,
      sessao_ids: ["sess_quiz_03"],
      labels: ["quiz"],
      checks: "vermelho",
      sincronizado_em: h(0.6),
    },
    {
      repo: ALMA_OS,
      numero: 41,
      titulo: "docs(prd): documento do OS-ADVISOR revisado",
      estado: "aberto",
      rascunho: false,
      branch: "claude/prd-advisor",
      base: "main",
      autor: "claude",
      url: "https://github.com/scudelerlucas/alma-petra-os/pull/41",
      criado_em: d(3),
      atualizado_em: h(26),
      fechado_em: null,
      mergeado_em: null,
      sessao_ids: [],
      labels: [],
      checks: "verde",
      sincronizado_em: h(0.6),
    },
    {
      repo: AIOX,
      numero: 207,
      titulo: "fix(lifeboard): tempo relativo em pt-BR na lista do dia",
      estado: "aberto",
      rascunho: false,
      branch: "claude/lifeboard-tempo",
      base: "main",
      autor: "claude",
      url: "https://github.com/scudelerlucas/aiox-core/pull/207",
      criado_em: d(1),
      atualizado_em: h(3),
      fechado_em: null,
      mergeado_em: null,
      sessao_ids: [],
      labels: [],
      checks: "pendente",
      sincronizado_em: h(0.6),
    },
    {
      repo: HUB,
      numero: 598,
      titulo: "docs(regras): check-in automático de mudança só onde há o que vigiar",
      estado: "mergeado",
      rascunho: false,
      branch: "claude/regra-checkin",
      base: "main",
      autor: "claude",
      url: "https://github.com/scudelerlucas/Lucas-Contexto-Geral/pull/598",
      criado_em: d(5),
      atualizado_em: d(3),
      fechado_em: d(3),
      mergeado_em: d(3),
      sessao_ids: [],
      labels: ["regra"],
      checks: "verde",
      sincronizado_em: h(0.6),
    },
    {
      repo: QUIZ,
      numero: 85,
      titulo: "feat(carta): carta do quiz revisada pelo auditor",
      estado: "mergeado",
      rascunho: false,
      branch: "claude/quiz-carta",
      base: "main",
      autor: "claude",
      url: "https://github.com/scudelerlucas/quiz-diagnosys/pull/85",
      criado_em: d(12),
      atualizado_em: d(9),
      fechado_em: d(9),
      mergeado_em: d(9),
      sessao_ids: ["sess_carta_07"],
      labels: [],
      checks: "verde",
      sincronizado_em: h(0.6),
    },
    {
      repo: ALMA_OS,
      numero: 38,
      titulo: "feat(cofre): pesos das moléculas no pacote público",
      estado: "fechado",
      rascunho: false,
      branch: "claude/cofre-publico",
      base: "main",
      autor: "claude",
      url: "https://github.com/scudelerlucas/alma-petra-os/pull/38",
      criado_em: d(8),
      atualizado_em: d(6),
      fechado_em: d(6),
      mergeado_em: null,
      sessao_ids: [],
      labels: [],
      checks: "vermelho",
      sincronizado_em: h(0.6),
    },
    {
      repo: AIOX,
      numero: 199,
      titulo: "refactor(core): fronteira L1/L4 do framework",
      estado: "aberto",
      rascunho: false,
      branch: "claude/fronteira-l1",
      base: "main",
      autor: "claude",
      url: "https://github.com/scudelerlucas/aiox-core/pull/199",
      criado_em: d(28),
      atualizado_em: d(20),
      fechado_em: null,
      mergeado_em: null,
      sessao_ids: [],
      labels: [],
      checks: null,
      sincronizado_em: h(0.6),
    },
    {
      repo: HUB,
      numero: 590,
      titulo: "docs(ops): frentes abertas de setembro",
      estado: "mergeado",
      rascunho: false,
      branch: "claude/frentes-abertas",
      base: "main",
      autor: "claude",
      url: "https://github.com/scudelerlucas/Lucas-Contexto-Geral/pull/590",
      criado_em: d(44),
      atualizado_em: d(40),
      fechado_em: d(40),
      mergeado_em: d(40),
      sessao_ids: [],
      labels: [],
      checks: "verde",
      sincronizado_em: h(0.6),
    },
    {
      repo: QUIZ,
      numero: 80,
      titulo: "feat(quiz): segundo motor de leitura do lead",
      estado: "fechado",
      rascunho: false,
      branch: "claude/quiz-segundo-motor",
      base: "main",
      autor: "claude",
      url: "https://github.com/scudelerlucas/quiz-diagnosys/pull/80",
      criado_em: d(50),
      atualizado_em: d(45),
      fechado_em: d(45),
      mergeado_em: null,
      sessao_ids: [],
      labels: [],
      checks: null,
      sincronizado_em: h(0.6),
    },
    {
      repo: AIOX,
      numero: 201,
      titulo: "feat(dashboard): custo por sessão no painel",
      estado: "aberto",
      rascunho: true,
      branch: "claude/custo-sessao",
      base: "main",
      autor: "claude",
      url: "https://github.com/scudelerlucas/aiox-core/pull/201",
      criado_em: d(6),
      atualizado_em: d(3),
      fechado_em: null,
      mergeado_em: null,
      sessao_ids: [],
      labels: [],
      checks: null,
      sincronizado_em: h(0.6),
    },
    {
      repo: HUB,
      numero: 605,
      titulo: "feat(lastro): lastro do canon vivo",
      estado: "aberto",
      rascunho: false,
      branch: "claude/lastro",
      base: "main",
      autor: "claude",
      url: "https://github.com/scudelerlucas/Lucas-Contexto-Geral/pull/605",
      criado_em: d(4),
      atualizado_em: h(30),
      fechado_em: null,
      mergeado_em: null,
      sessao_ids: ["sess_lastro_04"],
      labels: [],
      checks: "verde",
      sincronizado_em: h(0.6),
    },
    {
      repo: ALMA_OS,
      numero: 44,
      titulo: "feat(os-cas): três leituras de calibração",
      estado: "aberto",
      rascunho: false,
      branch: "claude/os-cas-calibra",
      base: "main",
      autor: "claude",
      url: "https://github.com/scudelerlucas/alma-petra-os/pull/44",
      criado_em: d(2),
      atualizado_em: h(4),
      fechado_em: null,
      mergeado_em: null,
      sessao_ids: ["sess_calibra_05"],
      labels: [],
      checks: "verde",
      sincronizado_em: h(0.6),
    },
  ];

  const branches: BranchSemPr[] = [
    {
      repo: HUB,
      branch: "claude/painel-assuntos",
      ultimo_commit_em: h(2),
      ultimo_commit_msg: "feat(painel): filtros por conta",
      sessao_ids: ["sess_painel_01"],
      tem_pr: true,
      sincronizado_em: h(0.6),
    },
    {
      repo: AIOX,
      branch: "claude/lifeboard-frentes",
      ultimo_commit_em: h(2),
      ultimo_commit_msg: "chore(lifeboard): esqueleto da tela de assuntos",
      sessao_ids: [],
      tem_pr: false,
      sincronizado_em: h(0.6),
    },
    {
      repo: QUIZ,
      branch: "claude/staging-botao",
      ultimo_commit_em: d(12),
      ultimo_commit_msg: "fix(quiz): tentativa no botão Iniciar do staging",
      sessao_ids: [],
      tem_pr: false,
      sincronizado_em: h(0.6),
    },
    {
      repo: ALMA_OS,
      branch: "claude/cofre-formulas",
      ultimo_commit_em: d(9),
      ultimo_commit_msg: "chore(cofre): move fórmulas para o COFRE",
      sessao_ids: [],
      tem_pr: false,
      sincronizado_em: h(0.6),
    },
    {
      repo: HUB,
      branch: "claude/docx-alma-petra",
      ultimo_commit_em: d(31),
      ultimo_commit_msg: "docs(docx): paleta ALMA PETRA nos documentos",
      sessao_ids: [],
      tem_pr: false,
      sincronizado_em: h(0.6),
    },
    {
      repo: HUB,
      branch: "claude/vigia-uptime",
      ultimo_commit_em: h(1),
      ultimo_commit_msg: "chore(vigia): domínios do cliente novo",
      sessao_ids: ["sess_vigia_02"],
      tem_pr: true,
      sincronizado_em: h(0.6),
    },
  ];

  const sessoes: Sessao[] = [
    {
      sessao_id: "sess_painel_01",
      conta: LUCAS,
      titulo: "Painel de assuntos das três contas",
      estado: "review_ready",
      estado_detalhe: "testes verdes, esperando aprovação",
      precisa_de: "você olhar e aprovar",
      branches: ["claude/painel-assuntos"],
      repos: [HUB],
      url: "https://claude.ai/code/session_painel01",
      criado_em: h(9),
      atualizado_em: h(2),
      custo_usd: 4.12,
      publicado_em: h(2),
    },
    {
      // Mesma branch da conversa de cima: as duas viram UM cartão, com dois links.
      sessao_id: "sess_painel_10",
      conta: PANDORA,
      titulo: "Revisão do painel de assuntos",
      estado: "working",
      estado_detalhe: "conferindo os textos da tela",
      precisa_de: null,
      branches: ["claude/painel-assuntos"],
      repos: [HUB],
      url: "https://claude.ai/code/session_painel10",
      criado_em: h(8),
      atualizado_em: h(3),
      custo_usd: 1.9,
      publicado_em: h(3),
    },
    {
      sessao_id: "sess_vigia_02",
      conta: LUCAS,
      titulo: "Vigia de uptime dos domínios",
      estado: "working",
      estado_detalhe: "escrevendo a lista de domínios",
      precisa_de: null,
      branches: ["claude/vigia-uptime"],
      repos: [HUB],
      url: "https://claude.ai/code/session_vigia02",
      criado_em: h(20),
      atualizado_em: h(1),
      custo_usd: 2.4,
      publicado_em: h(1),
    },
    {
      sessao_id: "sess_quiz_03",
      conta: PANDORA,
      titulo: "Quiz grava as métricas do ser",
      estado: "working",
      estado_detalhe: "corrigindo os testes",
      precisa_de: null,
      branches: ["claude/quiz-idforge"],
      repos: [QUIZ],
      url: "https://claude.ai/code/session_quiz03",
      criado_em: d(2),
      atualizado_em: h(5),
      custo_usd: 9.8,
      publicado_em: h(5),
    },
    {
      sessao_id: "sess_lastro_04",
      conta: ALMA,
      titulo: "Lastro do canon vivo",
      estado: "blocked",
      estado_detalhe: "falta a decisão do operador",
      precisa_de: "você dizer se o documento vira canon",
      branches: ["claude/lastro"],
      repos: [HUB],
      url: "https://claude.ai/code/session_lastro04",
      criado_em: d(4),
      atualizado_em: h(30),
      custo_usd: 6.05,
      publicado_em: h(30),
    },
    {
      sessao_id: "sess_calibra_05",
      conta: PANDORA,
      titulo: "Calibração do OS-CAS com três leituras",
      estado: "working",
      estado_detalhe: "montando as leituras de referência",
      precisa_de: null,
      branches: ["claude/os-cas-calibra"],
      repos: [ALMA_OS],
      url: "https://claude.ai/code/session_calibra05",
      criado_em: d(2),
      atualizado_em: h(4),
      custo_usd: 11.3,
      publicado_em: h(4),
    },
    {
      sessao_id: "sess_agenda_06",
      conta: LUCAS,
      titulo: "Agenda de falsificação das apostas",
      estado: "need_input",
      estado_detalhe: "sem dono para dois itens",
      precisa_de: "você dizer quem executa e quando",
      branches: [],
      repos: [],
      url: "https://claude.ai/code/session_agenda06",
      criado_em: d(1),
      atualizado_em: h(7),
      custo_usd: 1.15,
      publicado_em: h(7),
    },
    {
      sessao_id: "sess_carta_07",
      conta: ALMA,
      titulo: "Carta do quiz revisada pelo auditor",
      estado: "completed",
      estado_detalhe: "entregue e aprovada",
      precisa_de: null,
      branches: ["claude/quiz-carta"],
      repos: [QUIZ],
      url: "https://claude.ai/code/session_carta07",
      criado_em: d(12),
      atualizado_em: d(9),
      custo_usd: 7.7,
      publicado_em: d(9),
    },
    {
      sessao_id: "sess_triagem_08",
      conta: PANDORA,
      titulo: "Triagem do trabalho parado",
      estado: "idle",
      estado_detalhe: "parou no meio da varredura",
      precisa_de: null,
      branches: [],
      repos: [HUB],
      url: "https://claude.ai/code/session_triagem08",
      criado_em: d(13),
      atualizado_em: d(11),
      custo_usd: 3.3,
      publicado_em: d(11),
    },
    {
      sessao_id: "sess_poda_09",
      conta: LUCAS,
      titulo: "Poda da memória compartilhada",
      estado: "done",
      estado_detalhe: "resumos destilados",
      precisa_de: null,
      branches: [],
      repos: [HUB],
      url: "https://claude.ai/code/session_poda09",
      criado_em: d(6),
      atualizado_em: d(5),
      custo_usd: 2.05,
      publicado_em: d(5),
    },
  ];

  const sync: Sync[] = [
    {
      fonte: "github",
      executado_em: h(0.6),
      ok: true,
      itens: 14,
      erro: null,
    },
    {
      // De propósito velha: é o que acende o aviso âmbar de dados velhos.
      fonte: `sessoes:${ALMA}`,
      executado_em: d(3),
      ok: true,
      itens: 2,
      erro: null,
    },
  ];

  return { prs, branches, sessoes, sync };
}
